version: '3.8'  

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
      PGOPTIONS: "-c lock_timeout=30000"  # Increase lock timeout to 30 seconds
    ports:
      - "5438:5432"
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data

  redis:
    image: redis:6.2
    ports:
      - "6379:6379"

  airflow-init:
    build: .
    entrypoint: >
      bash -c "
      airflow db upgrade &&
      airflow users create -r Admin -u admin -p admin -e admin@example.com -f Admin -l User
      "
    environment:
      - AIRFLOW__CORE__FERNET_KEY
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    depends_on:
      - postgres
      - redis

  airflow-webserver:
    build: .
    command: webserver
    ports:
      - "8089:8080"
    environment:
      - AIRFLOW__CORE__FERNET_KEY
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    depends_on:
      - airflow-init

  airflow-scheduler:
    build: .
    command: scheduler
    environment:
      - AIRFLOW__CORE__FERNET_KEY
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    depends_on:
      - airflow-init

  airflow-worker:
    build: .
    command: celery worker
    environment:
      - AIRFLOW__CORE__FERNET_KEY
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    depends_on:
      - airflow-init

volumes:
  postgres-db-volume:
